### ISSUE TITLE
'login-sample': title of windows remains the same every time

### ISSUE THREAD

**Issue by ValeriusGC** [edvin/tornadofx-samples#26]
No matter which window loads first whether `LoginScreen` or `Workbench` the title remains like "Please, log in". Moreover there is no `label("If you can see this, you are successfully logged in!")` in the center of `workbench`.

I try to learn your library via these lessons so i get stuck with problem like this.

![image](https://user-images.githubusercontent.com/3320861/36712776-1e8c620a-1bac-11e8-9ed8-e83b7fad1e16.png)

**Comment by ValeriusGC** [comment]
Remark about `label("If you can see this, you are successfully logged in!`
Some minor changes in `workbench` fixed this issue

```java
center {

    vbox {
        alignment = Pos.CENTER

        label("If you can see this, you are successfully logged in!")

        hbox {
            alignment = Pos.CENTER

            button("Logout") {
                setOnAction {
                    loginController.logout()
                }
            }

            button("Exit") {
                setOnAction {
                    Platform.exit()
                }
            }
        }
    }

}
```
![image](https://user-images.githubusercontent.com/3320861/36716523-65ec506e-1bbc-11e8-93cc-86c2401250b0.png)

***

But until now i have no idea on how to fix "frozen" title of windows ...

**Comment by edvin** [comment]
I'm going over the sample now, it's horrendously outdated :) Give me a few minutes :)

**Comment by edvin** [comment]
I've updated the login sample to use `replaceWith`, which also takes care of keeping the stage title in sync:

```kotlin
secureScreen.replaceWith(loginScreen, sizeToScene = true, centerOnScreen = true)
```

There are also numerous other improvements to layout and handling in the login demo now.

**Comment by ValeriusGC** [comment]
Thanks, `Login` sample now works correctly. (Don'r know about other :) )

**Comment by edvin** [comment]
Great :) Can we close this issue?

**Comment by ValeriusGC** [comment]
of course ))

**Comment by edvin** [comment]
Perfect :)
