### ISSUE TITLE
login sample on mac and window7 different

### ISSUE THREAD

**Issue by igaoliang** [edvin/tornadofx-samples#31]
i clone the login sample, and run it on mac and window7.
but it seems different from each other.

the app run on mac.

<img width="301" alt="image" src="https://user-images.githubusercontent.com/13004562/40600812-5c04d912-6285-11e8-8397-f8b835fe7d3a.png">

and it run on win7.

<img width="268" alt="image" src="https://user-images.githubusercontent.com/13004562/40600860-80091ed6-6285-11e8-98ef-e927cb808254.png">

is there some args i should adjust on win ?

**Comment by edvin** [comment]
I looked at the sample and it should render the same on all platforms, provided you're not running a Java version that is as outdated as your OS :) Make sure you're running the latest JDK and try again. Mainstream support for Windows 7 ended in 2015, and even though extended support won't end for another two years,  Windows 7 isn't really a platform I see any value in debugging for unfortunately. Not sure I could even dig one up at this point.

**Comment by igaoliang** [comment]
thanks for your reply. i will test in latest jdk and win10.

**Comment by edvin** [comment]
Thank you :) But it would be interesting to see how it behaves in Windows 7 with the latest JDK as well :)

**Comment by igaoliang** [comment]
when i update the latest jdk 1.8_171 on win7. it looks fine.
so it may be the jdk's render problem.
Thanks!

**Comment by edvin** [comment]
Yeah, that's what I was hoping it would be. Good to know, thanks :)
