### ISSUE TITLE
Could you add some instructions about how to run the examples in README?

### ISSUE THREAD

**Issue by freewind** [edvin/tornadofx-samples#32]
I cloned the code and downloaded maven, but not sure how to run the examples. Could you add some simple instructions for beginners?

**Comment by edvin** [comment]
Hi! Each sample has an App subclass which contains a `main` method. Open the sample in your IDE and goto the App class, for example for the Login app, this would be `LoginApp.kt`. If you have the TornadoFX IDEA plugin installed, click the play button in the gutter next to the `LoginApp` class, if you don't have the plugin installed you can click the play button in the gutter next to the `main` function.
