### ISSUE TITLE
Would be nice to upgrade to Kotlin 1.3.

### ISSUE THREAD

**Issue by Krzyjan** [edvin/tornadofx-samples#39]

**Comment by edvin** [comment]
I agree. Would you like to submit a PR?

**Comment by Krzyjan** [comment]
> 
> 
> I agree. Would you like to submit a PR?

He-he. It's a loaded question ;-). I am fairly new to Kotlin and TornadoFX. I can give it a shot , though. I would be aiming at Kotlin 1.5.10 and TornadoFX 1.7.20. If you can think of any reason why this wouldn't work, please let me know.

**Comment by edvin** [comment]
Hehe, yeah I tried to be sneaky :) Isn't 1.5 still experimental? If that's the case you might want to opt for 1.4, for the samples I guess it doesn't matter much. The core lib might need to be updated as well, and there I think it would be smart to go for latest stable, so perhaps you'd like to do the same her. In any case I don't think it would entail a lot of work. Try it and see what doesn't compile basically.

**Comment by Krzyjan** [comment]
Here is my progress report. I have bumped up both Kotlin and TornadoFX to 1.5.21 and 1.7.20 respectively. As you said, compiling was fairly easy. Getting some of it to run proved to be a bit more of a challenge. I have done forms so far. I have also got rid of some of the more annoying Maven warnings. Now, I will be trying to run the other samples.
Let me know, please, if you want me to submit the PR as it stands now, or you would rather wait for the rest?

**Comment by Krzyjan** [comment]
I am not sure what the protocol here is. I have created a pull request: https://github.com/edvin/tornadofx-samples/pull/40.

**Comment by Krzyjan** [comment]
Since the PR has been merged, I am closing this issue.
